CREATE TABLE `viagem_compartilhamento` (
	`ID_VIAGEM_COMPARTILHAMENTO` BIGINT(19) NOT NULL AUTO_INCREMENT,
	`ID_VIAGEM` BIGINT(19) NOT NULL,
	`ID_USUARIO` INT UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID_VIAGEM_COMPARTILHAMENTO`),
	KEY `FK_VIAGEM_COMPARTILHAMENTO_USUARIO` (`ID_USUARIO`),
	KEY `FK_VIAGEM_COMPARTILHAMENTO_VIAGEM` (`ID_VIAGEM`),
	CONSTRAINT `FK_VIAGEM_COMPARTILHAMENTO_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuario` (`ID_USUARIO`) ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT `FK_VIAGEM_COMPARTILHAMENTO_VIAGEM` FOREIGN KEY (`ID_VIAGEM`) REFERENCES `viagem` (`ID_VIAGEM`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;