CREATE TABLE IF NOT EXISTS `google_calendar_token` (
  `ID_GOOGLE_TOKEN` BIGINT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT UNSIGNED NOT NULL,
  `DS_ACCESS_TOKEN` TEXT NOT NULL,
  `DS_REFRESH_TOKEN` TEXT NOT NULL,
  `DT_EXPIRACAO` DATETIME NOT NULL,
  `DS_EMAIL_GOOGLE` VARCHAR(255) DEFAULT NULL,
  `DS_SCOPES` VARCHAR(1000) DEFAULT NULL,
  `DT_CRIACAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DT_ATUALIZACAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_GOOGLE_TOKEN`),
  UNIQUE KEY `UK_GOOGLE_TOKEN_USUARIO` (`ID_USUARIO`),
  CONSTRAINT `FK_GOOGLE_TOKEN_USUARIO` FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `usuario` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
