CREATE TABLE IF NOT EXISTS `google_calendar_selecao` (
  `ID_CALENDAR_SELECAO` BIGINT NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` INT UNSIGNED NOT NULL,
  `DS_CALENDAR_ID` VARCHAR(500) NOT NULL,
  `NM_CALENDAR` VARCHAR(255) NOT NULL,
  `DS_COR` VARCHAR(20) DEFAULT NULL,
  `FG_ATIVO` BIT(1) NOT NULL DEFAULT b'1',
  `DT_CRIACAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_CALENDAR_SELECAO`),
  UNIQUE KEY `UK_SELECAO_USUARIO_CAL` (`ID_USUARIO`, `DS_CALENDAR_ID`),
  CONSTRAINT `FK_CALENDAR_SELECAO_USUARIO` FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `usuario` (`ID_USUARIO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
